add time build for mlir
sophgo/tpu-perf pull request #30
Opened 2023-02-24 10:28 UTC by XiangBin-gh

2023-02-24 12:50 UTC, Jeffwhen requested changes

2023-02-24 12:50 UTC, Jeffwhen commented on python/tpu_perf/build.py
> +        pool.put('cali_key', cali_cmd)
引号去掉。

2023-02-28 07:32 UTC, closed without merging

2023-02-28 07:32 UTC, XiangBin-gh commented
need modifiy

2023-02-28 07:33 UTC, XiangBin-gh commented
need modify