multi devices support
sophgo/tpu-perf pull request #33
Opened 2023-03-13 02:01 UTC by huwolong

review一下吧

2023-03-13 07:01 UTC, Jeffwhen requested changes

2023-03-13 07:01 UTC, Jeffwhen commented on python/tpu_perf/run.py
> +USE_ALL_DEVICES = False
格式和下面的变量名保持一致。

2023-03-13 07:01 UTC, Jeffwhen commented on python/tpu_perf/run.py
> +        stats["shape"] = res["shape"]
把 throughput 也写进去。

2023-03-15 02:13 UTC, huwolong commented on python/tpu_perf/run.py
> +        stats["shape"] = res["shape"]
好了，再看看吧

2023-03-22 02:51 UTC, closed without merging